
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost
  port: 5432


development:
  <<: *default
  database: learner_development

  
test:
  <<: *default
  database: learner_test


production:
  <<: *default
  database: learner_production
  username: learner
  password: <%= ENV['LEARNER_DATABASE_PASSWORD'] %>
